# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G -Djava.net.preferIPv4Stack=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties
mc_version=1.20.1
mc_range=[1.20.1,1.21)
forge_version=47.3.28
forge_version_range=[47,)
loader_version_range=[47,)

# Parchment mappings, see https://parchmentmc.org/docs/getting-started
mapping_version=2023.09.03

## Mod Properties
mod_id=neb
mod_name=NotEnoughBandwidth
mod_platform=forge
mod_license=GNU GPL 3.0
mod_version=1.0.0
mod_version_tag=alpha
mod_group_id=cn.ussshenzhou
mod_authors=USS_Shenzhou
mod_description=Compresses and aggregates server-to-client network traffic.
issue_tracker=https://github.com/USS-Shenzhou/NotEnoughBandwidth/issues

## Dependency Versions
zstd_version=1.5.6-9
